development:
  bucket: 394_Blue 
  access_key_id: AKIAJA5A2DHVDPAFUMHA
  secret_access_key: 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 
  max_file_size: 10485760
  acl: public-read
    
test:
  bucket: 394_Blue 
  access_key_id: AKIAJA5A2DHVDPAFUMHA
  secret_access_key: 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 
  max_file_size: 10485760
  acl: public-read
  
production:
  bucket: 394_Blue 
  access_key_id: AKIAJA5A2DHVDPAFUMHA
  secret_access_key: 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 
  max_file_size: 10485760
  acl: public-read
